name: Sync to S3
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Wipe S3
      run: aws s3 rm s3://tucker-portfolio-bucket --recursive
    
    - name: Sync to S3
      run: aws s3 sync ./favicon.png s3://tucker-portfolio-bucket & \
           aws s3 sync ./index.html s3://tucker-portfolio-bucket & \
           aws s3 sync ./main.js s3://tucker-portfolio-bucket & \
           aws s3 sync ./main.ccc s3://tucker-portfolio-bucket & \
           aws s3 sync ./resources s3://tucker-portfolio-bucket & \
           aws s3 sync ./index.html s3://tucker-portfolio-bucket & \
           aws s3 sync ./package-lock.json s3://tucker-portfolio-bucket & \
           aws s3 sync ./package.json s3://tucker-portfolio-bucket 
