name: Sync to S3
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Install Dependencies
      run: npm install
    
    - name: Webpack the Modules
      run: npm run pack
    
    - name: Sync Public Folder to S3
      run: aws s3 sync ./public s3://tucker-portfolio-bucket/public --delete
    
    - name: Sync Dist Folder to S3
      run: aws s3 sync ./dist s3://tucker-portfolio-bucket/dist --delete

    - name: Invalid Cache for Index
      run: aws cloudfront create-invalidation --distribution-id E2FEOX49TU64QS --paths "/*"
